name: Build

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: yarn --frozen-lockfile
      working-directory: ./renderer
    - run: yarn make-index-files
      working-directory: ./renderer
    - run: yarn lint
      working-directory: ./renderer
    - run: yarn build
      working-directory: ./renderer
    - uses: actions/upload-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
        retention-days: 1

  package:
    needs: renderer
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - uses: actions/download-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
    - run: yarn --frozen-lockfile
      working-directory: ./main
    - run: yarn build
      working-directory: ./main
    - run: yarn package -p always
      working-directory: ./main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Hash
      run: type .\main\dist\latest.yml
      
    - name: Upload packaged files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-files
        path: |
          ./main/dist/*.exe
          ./main/dist/*.zip
          ./main/dist/latest.yml

    - name: Install GitHub CLI
      uses: cli/cli@v2

    - name: Create Release if not exists
      run: |
        gh release view latest || gh release create latest --notes "Auto build"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Release
      run: |
        gh release upload latest ./main/dist/*.exe --clobber
        gh release upload latest ./main/dist/*.zip --clobber
        gh release upload latest ./main/dist/latest.yml --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
