name: Build

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: yarn --frozen-lockfile
      working-directory: ./renderer
    - run: yarn make-index-files
      working-directory: ./renderer
    - run: yarn lint
      working-directory: ./renderer
    - run: yarn build
      working-directory: ./renderer
    - uses: actions/upload-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
        retention-days: 1

  package:
    needs: renderer
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - uses: actions/download-artifact@v4
      with:
        name: renderer-dist
        path: ./renderer/dist
    - run: yarn --frozen-lockfile
      working-directory: ./main
    - run: yarn build
      working-directory: ./main
    - run: yarn package -p always
      working-directory: ./main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Hash
      run: type .\main\dist\latest.yml
